from .config import (
    METHOD_PROMPTMATCH,
    METHOD_IMAGEREWARD,
    METHOD_LLMSEARCH,
    METHOD_SIMILARITY,
    METHOD_SAMEPERSON,
    METHOD_TAGMATCH,
    DEFAULT_IR_PENALTY_WEIGHT,
    DEFAULT_LLMSEARCH_BACKEND,
    LLMSEARCH_SHORTLIST_DEFAULT,
    DEFAULT_PROMPT_GENERATOR,
    DEFAULT_GENERATED_PROMPT_DETAIL,
)


def get_state_defaults(source_dir=None, prompt_backend=None):
    return {
        "method": METHOD_PROMPTMATCH,
        "source_dir": source_dir,
        "view_mode": "scored",
        "browse_items": [],
        "browse_status": "",
        "scores": {},
        "overrides": {},
        "last_scored_method": None,
        "last_scored_folder_key": None,
        "last_promptmatch_model_label": None,
        "left_marked": [],
        "right_marked": [],
        "preview_fname": None,
        "backend": prompt_backend,
        "ir_model": None,
        "face_backend": None,
        "tagmatch_backend": None,
        "hist_geom": None,
        "hist_width": 300,
        "proxy_folder_key": None,
        "proxy_cache_dir": None,
        "proxy_signature": None,
        "proxy_map": {},
        "use_proxy_display": True,
        "ir_penalty_weight": DEFAULT_IR_PENALTY_WEIGHT,
        "pm_cached_signature": None,
        "pm_cached_model_label": None,
        "pm_cached_feature_paths": None,
        "pm_cached_image_features": None,
        "pm_cached_failed_paths": None,
        "pm_segment_mode": False,
        "pm_segment_sims": {},
        "face_cached_signature": None,
        "face_cached_feature_paths": None,
        "face_cached_embeddings": None,
        "face_cached_failures": None,
        "ir_cached_signature": None,
        "ir_cached_positive_prompt": None,
        "ir_cached_negative_prompt": None,
        "ir_cached_base_scores": None,
        "ir_cached_penalty_scores": None,
        "llmsearch_backend": DEFAULT_LLMSEARCH_BACKEND,
        "llmsearch_shortlist_size": LLMSEARCH_SHORTLIST_DEFAULT,
        "llmsearch_cached_signature": None,
        "llmsearch_cached_prompt": None,
        "llmsearch_cached_backend": None,
        "llmsearch_cached_scoring_mode": None,
        "llmsearch_cached_shortlist_size": None,
        "llmsearch_cached_model_label": None,
        "llmsearch_cached_scores": None,
        "llmsearch_cached_captions": {},
        "tagmatch_cached_signature": None,
        "tagmatch_cached_feature_paths": None,
        "tagmatch_cached_tag_vectors": None,
        "tagmatch_last_query_tags_str": "",
        "tagmatch_vocab_tags": None,
        "tagmatch_vocab_json": "[]",
        "prompt_generator": DEFAULT_PROMPT_GENERATOR,
        "prompt_backend_cache": {},
        "generated_prompt": "",
        "generated_prompt_source": None,
        "generated_prompt_backend": DEFAULT_PROMPT_GENERATOR,
        "generated_prompt_detail": DEFAULT_GENERATED_PROMPT_DETAIL,
        "generated_prompt_variants": {},
        "generated_prompt_status": "Preview, drop, paste, or upload an image, then generate a prompt from it.",
        "external_query_path": None,
        "external_query_label": None,
        "external_query_active": False,
        "external_query_signature": None,
        "similarity_query_fname": None,
        "similarity_query_source": None,
        "similarity_model_label": None,
        "sameperson_query_fname": None,
        "sameperson_query_source": None,
        "sameperson_model_label": None,
        "mode_thresholds": {
            METHOD_PROMPTMATCH: {"main": None, "aux": None},
            METHOD_IMAGEREWARD: {"main": None, "aux": None},
            METHOD_LLMSEARCH: {"main": None, "aux": None},
            METHOD_SIMILARITY: {"main": None, "aux": None},
            METHOD_SAMEPERSON: {"main": None, "aux": None},
            METHOD_TAGMATCH: {"main": None, "aux": None},
        },
        "zoom_columns": 5,
    }


def init_state(source_dir=None, prompt_backend=None):
    return dict(get_state_defaults(source_dir, prompt_backend))
